- name: install nginx
  host: mangodb
  become: yes
  vars:
    NAME: nginx

  tasks:
  - name: install nginx
    ansible.builtin.yum:
      name: nginx
      state: installed

  - name: start server
    ansible.builtin.service:
      state: restarted
      enabled: true

  - name: print something 
    ansible.builtin.debug:
      msg: "{{NAME}} installed"    

