- name: practice prompt variables
  hosts: localhost

  vars_prompt:
  - name: USERNAME
    prompt: enter user_name
    private: no
  - name: PASSWORD  
    prompt: enter password
    private: yes
  tasks:
  - name: print the prompt values
    ansible.builtin.debug:
      msg: "username: {{USERNAME}} and password: {{PASSWORD}}" 
      
       

